name: Generate Site

on:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: List Google Drive folder contents
              env:
                  SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
              run: |
                  echo "$SERVICE_ACCOUNT_JSON" > service_account.json
                  python3 src/docs_site_generator
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.ACCESS_TOKEN }}
                  publish_dir: ./build
                  external_repository: jancharatan/jancharatan.github.io
